name: Opstella - Get Kubeconfig
on:
  workflow_call:
    inputs:
      cluster_name:
        description: "Name of the cluster"
        required: true
        type: string
      resource_group:
        description: "Name of the resource group"
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        description: "Azure credentials in JSON format"
        required: true

  workflow_dispatch:
    inputs:
      cluster_name:
        description: "Name of the cluster"
        required: true
        type: string
      resource_group:
        description: "Name of the resource group"
        required: true
        type: string
jobs:
  Azure_Login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  Get_Kubeconfig:
    needs: Azure_Login
    runs-on: ubuntu-latest
    steps:
      - name: Get Kubeconfig
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az aks get-credentials -g ${{ inputs.resource_group }} -n ${{ inputs.cluster_name }} --file ./temp_kubeconfig --admin --overwrite-existing
            HOST=$(grep "server:" ./temp_kubeconfig | awk '{print $2}' | head -n 1)
            CA_CERT=$(grep "certificate-authority-data:" ./temp_kubeconfig | awk '{print $2}' | head -n 1)
            CLIENT_KEY=$(grep "client-key-data:" ./temp_kubeconfig | awk '{print $2}' | head -n 1)
            jq -n \
            --arg name "${{ inputs.cluster_name }}" \
            --arg host "$HOST" \
            --arg key "$CLIENT_KEY" \
            --arg ca "$CA_CERT" \
            '{
              name: $name,
              host: $host,
              port: "",
              "api-key": $key,
              "ca-cert": $ca
            }' > cluster-metadata.json

      - name: Upload Metadata
        uses: actions/upload-artifact@v4
        with:
          name: cluster-info-output
          path: cluster-metadata.json
          retention-days: 14
