name: Opstella - Get Kubeconfig
on:
  workflow_call:
    inputs:
      cluster_name:
        description: "Name of the cluster"
        required: true
        type: string
      resource_group:
        description: "Name of the resource group"
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        description: "Azure credentials in JSON format"
        required: true

  workflow_dispatch:
    inputs:
      cluster_name:
        description: "Name of the cluster"
        required: true
        type: string
      resource_group:
        description: "Name of the resource group"
        required: true
        type: string
jobs:
  Get_Kubeconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Check Tool Versions
        run: |
          az --version
          python3 --version
          jq --version
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get Kubeconfig
        run: |
          az aks get-credentials -g ${{ inputs.resource_group }} -n ${{ inputs.cluster_name }} --file ./temp_kubeconfig --admin --overwrite-existing
          HOST=$(yq -r '.clusters[0].cluster.server' ./temp_kubeconfig)
          CA_CERT=$(yq -r '.clusters[0].cluster.certificate-authority-data' ./temp_kubeconfig)
          CLIENT_KEY=$(yq -r '.users[0].user.client-key-data' ./temp_kubeconfig)
          jq -n \
          --arg name "${{ inputs.cluster_name }}" \
          --arg host "$HOST" \
          --arg key "$CLIENT_KEY" \
          --arg ca "$CA_CERT" \
          '{
            name: $name,
            host: $host,
            port: "",
            "api-key": $key,
            "ca-cert": $ca
          }' > cluster-metadata.json

      - name: Upload Metadata
        uses: actions/upload-artifact@v4
        with:
          name: cluster-info-output
          path: cluster-metadata.json
          retention-days: 14
