name: Opstella - Get Kubeconfig
on:
  workflow_call:
    inputs:
      cluster_name:
        description: "Name of the cluster"
        required: true
        type: string
      resource_group:
        description: "Name of the resource group"
        required: true
        type: string
      runner_label:
        description: "Label of the runner to execute the workflow"
        required: true
        type: string
      azure_client_id:
        description: "Azure Client ID"
        required: true
        type: string
      azure_tenant_id:
        description: "Azure Tenant ID"
        required: true
        type: string
    secrets:
      AZURE_CLIENT_SECRET:
        description: "Azure Client Secret"
        required: true

  workflow_dispatch:
    inputs:
      cluster_name:
        description: "Name of the cluster"
        required: true
        type: string
      resource_group:
        description: "Name of the resource group"
        required: true
        type: string
jobs:
  Get_Kubeconfig:
    runs-on: ${{ inputs.runner_label }}
    steps:
      - name: install prerequisites
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          sudo apt update && sudo apt-get install wget -y
          sudo apt-get install jq
          sudo apt-get install yq

      - name: Get Kubeconfig
        run: |
          az login --service-principal -u ${{ inputs.azure_client_id }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ inputs.azure_tenant_id }}
          az aks get-credentials -g ${{ inputs.resource_group }} -n ${{ inputs.cluster_name }} --file ./temp_kubeconfig --admin --overwrite-existing
          HOST=$(yq -r '.clusters[0].cluster.server' ./temp_kubeconfig | sed 's/:[0-9]*$//')
          CA_CERT=$(yq -r '.clusters[0].cluster.certificate-authority-data' ./temp_kubeconfig)
          CLIENT_KEY=$(yq -r '.users[0].user.client-key-data' ./temp_kubeconfig)
          jq -n \
          --arg name "${{ inputs.cluster_name }}" \
          --arg host "$HOST" \
          --arg key "$CLIENT_KEY" \
          --arg ca "$CA_CERT" \
          '{
            name: $name,
            host: $host,
            port: "",
            "apiKey": $key,
            "caCert": $ca
          }' > cluster-metadata.json

      - name: Upload Metadata
        uses: actions/upload-artifact@v4
        with:
          name: cluster-info-output
          path: cluster-metadata.json
          retention-days: 14
