name: Opstella Terraform Pipeline Caller ##
on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]
  repository_dispatch:
    types: [ before-approve ]
jobs:
  pipeline:
    uses: ./.github/workflows/pipeline.yml
    secrets: inherit
    permissions:
      issues: write
      contents: read
    with:
      terraform_directory: "terraform"
      allow_failed_security_gate: true
      arm_client_id: ${{ vars.ARM_CLIENT_ID }}
      arm_tenant_id: ${{ vars.ARM_TENANT_ID }}
      arm_subscription_id: ${{ vars.ARM_SUBSCRIPTION_ID }}
    # var_file: 'terraform/values.tfvars'
