name: Opstella Terraform pipeline
on:
  workflow_call:
    inputs:
      runner_label:
        description: "The label of the runner to execute the pipeline on"
        required: false
        default: "gcloud-runner-set-custom"
        type: string
      trivy_iac_report_filename:
        description: "The filename for the Trivy IaC report"
        required: false
        default: "trivy-iac-report.json"
        type: string
      terraform_plan_output_filename:
        description: "The filename for the Terraform plan output"
        required: false
        default: "terraform-plan-output"
        type: string
      report_retention_days:
        description: "Number of days to retain the reports"
        required: false
        default: 7
        type: number

      terraform_directory:
        description: "Directory containing Terraform configuration"
        required: false
        default: "."
        type: string
      allow_failed_security_gate:
        description: "Allow pipeline to continue even if security gate fails"
        required: false
        default: false
        type: boolean
      var_file:
        description: "Optional Terraform variables file path"
        required: false
        type: string

      backend_config_file:
        description: "Backend config file for Terraform init (optional)"
        required: false
        type: string

      arm_client_id:
        description: "Azure Client ID for Terraform"
        required: true
        type: string

      arm_tenant_id:
        description: "Azure Tenant ID for Terraform"
        required: true
        type: string

      arm_subscription_id:
        description: "Azure Subscription ID for Terraform"
        required: true
        type: string

      app_id:
        description: "GitHub App Client ID used to generate installation tokens"
        required: true
        type: string

    secrets:
      GH_PRIVATE_KEY:
        description: "GitHub App private key used to generate installation tokens"
        required: true
      ARM_CLIENT_SECRET:
        description: "Azure Client Secret"
        required: true

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
  ARM_CLIENT_ID: ${{ inputs.arm_client_id }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ inputs.arm_tenant_id }}
  ARM_SUBSCRIPTION_ID: ${{ inputs.arm_subscription_id }}
jobs:

  check-secret-and-variables:
    runs-on: ${{ inputs.runner_label }}
    steps:
      - name: Check if GitHub App configuration is set
        run: |
          if [ -z "${{ inputs.app_id }}" ]; then
            echo "Error: app_id input is not set. Exiting..."
            exit 1
          fi

          if [ -z "${{ secrets.GH_PRIVATE_KEY }}" ]; then
            echo "Error: GH_PRIVATE_KEY secret is not set. Exiting..."
            exit 1
          else
            echo "GitHub App configuration is set."
          fi
  # Step1 : Terraform Format Check
  terraform-format:
    runs-on: ${{ inputs.runner_label }}
    needs: check-secret-and-variables
    if: ${{ !cancelled() && always()}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - &create-plugin-cache-dir
        name: Create Plugin Cache Dir
        run: mkdir -p $TF_PLUGIN_CACHE_DIR

      - &restore-cache-terraform-providers
        name: Restore Terraform Cache
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ hashFiles('terraform/.terraform.lock.hcl')
            }}
      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.5.7
      #     terraform_wrapper: false

      - &create-github-app-token
        name: Create GitHub App installation token
        id: app-token
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ inputs.app_id }}
          private-key: ${{ secrets.GH_PRIVATE_KEY }}

      - &setup-token-for-git
        name: Configure Git with GitHub App token
        run: |
          git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf "https://github.com/"
      - &bump-az-credential
        name: Update Azure Credentials in Terraform Files
        run: |
          SUBSCRIPTION_ID="${{ inputs.arm_subscription_id }}"
          TENANT_ID="${{ inputs.arm_tenant_id }}"

          # Update tfvars - replace credential values while preserving other content
          sed -i "s/tenant_id[[:space:]]*=[[:space:]]*\"[^\"]*\"/tenant_id       = \"$TENANT_ID\"/" "${{ inputs.var_file }}"
          sed -i "s/subscription_id[[:space:]]*=[[:space:]]*\"[^\"]*\"/subscription_id = \"$SUBSCRIPTION_ID\"/" "${{ inputs.var_file }}"
          # sed -i "s/client_id[[:space:]]*=[[:space:]]*\"[^\"]*\"/client_id       = \"$CLIENT_ID\"/" "${{ inputs.var_file }}"
          # sed -i "s/client_secret[[:space:]]*=[[:space:]]*\"[^\"]*\"/client_secret   = \"$CLIENT_SECRET\"/" "${{ inputs.var_file }}"

      - &terraform-init
        name: Terraform Init
        run: |
          BACKEND_CONFIG=""
          if [ -n "${{ inputs.backend_config_file }}" ]; then
            # Use absolute path from workspace root
            BACKEND_CONFIG_PATH="${{ github.workspace }}/${{ inputs.backend_config_file }}"
            BACKEND_CONFIG="-backend-config=$BACKEND_CONFIG_PATH"
          fi
          terraform -chdir=${{ inputs.terraform_directory }} init $BACKEND_CONFIG -input=false

      - name: Terraform Format Check
        id: fmt
        run: |
          terraform -chdir=${{ inputs.terraform_directory }} fmt -recursive

      - &save-cache-terraform-providers
        name: Save Terraform Cache
        if: steps.restore-cache.outputs.cache-hit != 'true' && github.ref ==
          'refs/heads/main'
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}

  # Step2 : Terraform validate
  terraform-validate:
    runs-on: ${{ inputs.runner_label }}
    if: ${{ !cancelled() && always() && needs.terraform-format.result == 'success'}}
    needs: terraform-format
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - *create-plugin-cache-dir

      - *restore-cache-terraform-providers

      - *create-github-app-token

      - *setup-token-for-git
      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.5.7
      #     terraform_wrapper: false

      - *bump-az-credential
      - *terraform-init
      - name: Terraform Validate
        run: |
          terraform -chdir=${{ inputs.terraform_directory }} validate || (echo "Error: Terraform validation failed." && exit 1)

      - *save-cache-terraform-providers

      - name: List files
        run: ls -R ${{ inputs.terraform_directory }}

  # Step3 : TF Lint
  terraform-lint:
    runs-on: ${{ inputs.runner_label }}
    if: ${{ !cancelled() && always() && needs.terraform-validate.result ==
      'success'}}
    needs: terraform-validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.5.7
      #     terraform_wrapper: false

      - *restore-cache-terraform-providers

      - *create-github-app-token

      - *setup-token-for-git
      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run tflint
        run: |
          cd ${{ inputs.terraform_directory }}
          tflint --init --force || true
          tflint -f compact --force || true
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - *save-cache-terraform-providers

      - name: List files
        run: ls -R ${{ inputs.terraform_directory }}
  # Step4 : Trivy IaC Scan
  Trivy-IAC-scan:
    runs-on: ${{ inputs.runner_label }}
    if: ${{ !cancelled() && always() && needs.terraform-lint.result == 'success'}}
    needs: terraform-lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Install Helm
      #   uses: azure/setup-helm@v4

      - *create-github-app-token

      - *terraform-init

      - name: Generate Trivy IaC Vulnerability Report
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: "fs"
          scan-ref: .
          scanners: "misconfig,secret"
          format: json
          # trivyignores: .trivyignore
          output: ${{ inputs.trivy_iac_report_filename }}
          exit-code: ${{ inputs.allow_failed_security_gate == true && '0' || '1' }}
          severity: "HIGH,CRITICAL"

      - name: Upload Trivy IaC Report
        uses: actions/upload-artifact@v6
        with:
          name: trivy-iac-report
          path: |
            ${{ inputs.trivy_iac_report_filename }}
          retention-days: ${{ inputs.report_retention_days }}

  # Step5 : Terraform Plan
  terraform-plan:
    runs-on: ${{ inputs.runner_label }}
    if: ${{ !cancelled() && always() && needs.Trivy-IAC-scan.result == 'success'}}
    needs: Trivy-IAC-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - *create-plugin-cache-dir

      - *restore-cache-terraform-providers

      - *create-github-app-token

      - *setup-token-for-git

      # - &setup-python
      #   name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.x"

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.5.7
      #     terraform_wrapper: false

      - *bump-az-credential

      - *terraform-init

      - name: Terraform Plan
        run: |
          VAR_FILE_ARGS=""
          if [ -n "${{ inputs.var_file }}" ]; then
            # Use absolute path from workspace root
            VAR_FILE_PATH="${{ github.workspace }}/${{ inputs.var_file }}"
            VAR_FILE_ARGS="-var-file=$VAR_FILE_PATH"
          fi
          terraform plan -out=plan.tfplan $VAR_FILE_ARGS || exit 1
        working-directory: ./${{ inputs.terraform_directory }}

      - name: Terraform form Plan Output
        run: |
          terraform show -json plan.tfplan > "${{ inputs.terraform_plan_output_filename }}.json"
        working-directory: ./${{ inputs.terraform_directory }}

      - name: list files
        run: ls -R ${{ inputs.terraform_directory }}
      - name: Upload Terraform Plan Output
        uses: actions/upload-artifact@v6
        with:
          name: terraform-plan-output-json
          path: "${{ inputs.terraform_directory }}/${{
            inputs.terraform_plan_output_filename }}.json"
          retention-days: ${{ inputs.report_retention_days }}
      - name: Install tfplan2md
        run: |
          VERSION="1.40.0"
          PLATFORM="linux-x64"
          curl -L -o tfplan2md_${VERSION}_${PLATFORM}.tar.gz "https://github.com/oocx/tfplan2md/releases/download/v${VERSION}/tfplan2md_${VERSION}_${PLATFORM}.tar.gz"
          tar -xzf tfplan2md_${VERSION}_${PLATFORM}.tar.gz
          ./tfplan2md --help
          od -c -N 10 ${{ inputs.terraform_plan_output_filename }}.json
          ./tfplan2md "${{ inputs.terraform_plan_output_filename }}.json" -o "${{ inputs.terraform_plan_output_filename }}.md"
          ls -l "${{ inputs.terraform_plan_output_filename }}.md"
        working-directory: ./${{ inputs.terraform_directory }}

      - name: Upload Terraform Plan Output
        uses: actions/upload-artifact@v6
        with:
          name: terraform-plan-output
          path: "${{ inputs.terraform_directory }}/${{
            inputs.terraform_plan_output_filename }}.md"
          retention-days: ${{ inputs.report_retention_days }}

      - *save-cache-terraform-providers

  wait-for-approval:
    runs-on: ${{ inputs.runner_label }}
    if: ${{ !cancelled() && always() && needs.terraform-plan.result == 'success'}}
    needs: terraform-plan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - *create-github-app-token

      - name: Check if artifact exists
        run: |
          echo "Checking for Terraform plan artifact..."
          gh run download ${{ github.run_id }} --name terraform-plan-output --dir ./artifact || { echo "Artifact not found! Exiting..."; exit 1; }
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Wait for PR Approval
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Waiting for the 'deploy-to-cd' label on PR #$PR_NUMBER..."

          gh pr edit $PR_NUMBER --add-label "waiting-for-approval"

          MAX_RETRIES=20
          RETRY_COUNT=0
          INTERVAL=20

          until [ $RETRY_COUNT -ge $MAX_RETRIES ]; do 
            # Check if the PR has the specific label
            HAS_LABEL=$(gh pr view $PR_NUMBER --json labels --jq '.labels[] | select(.name == "deploy-to-cd") | .name')

            if [ "$HAS_LABEL" == "deploy-to-cd" ]; then
              echo "Label detected! Starting CD..."
              gh pr edit $PR_NUMBER --remove-label "deploy-to-cd"
              break
            fi

            echo "Still waiting for label... (checking again in 20s)"
            sleep $INTERVAL
          done
          gh pr edit $PR_NUMBER --remove-label "waiting-for-approval"

  terraform-apply:
    runs-on: ${{ inputs.runner_label }}
    if: ${{ success() }}
    needs: wait-for-approval
    outputs:
      cluster_name: ${{ steps.tf-output.outputs.cluster_name }}
      node_resource_group_name: ${{ steps.tf-output.outputs.node_resource_group_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - *setup-python

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.5.7
      #     terraform_wrapper: false

      - *create-github-app-token

      - *setup-token-for-git

      - *bump-az-credential

      - *terraform-init

      - name: Terraform Apply
        run: |
          VAR_FILE_ARGS=""
          if [ -n "${{ inputs.var_file }}" ]; then
            # Use absolute path from workspace root
            VAR_FILE_PATH="${{ github.workspace }}/${{ inputs.var_file }}"
            VAR_FILE_ARGS="-var-file=$VAR_FILE_PATH"
          fi
          terraform -chdir=${{ inputs.terraform_directory }} apply -parallelism=1 -auto-approve $VAR_FILE_ARGS

      - name: Extract Terraform Outputs
        id: tf-output
        run: |
          CLUSTER_NAME=$(terraform -chdir=${{ inputs.terraform_directory }} output -raw cluster_name)
          NODE_RESOURCE_GROUP=$(terraform -chdir=${{ inputs.terraform_directory }} output -raw node_resource_group_name)
          echo "cluster_name=$CLUSTER_NAME" >> $GITHUB_OUTPUT
          echo "node_resource_group_name=$NODE_RESOURCE_GROUP" >> $GITHUB_OUTPUT
          echo "Extracted cluster_name: $CLUSTER_NAME"
          echo "Extracted node_resource_group_name: $NODE_RESOURCE_GROUP"

      - name: Close PR via CLI
        run: gh pr close ${{ github.event.pull_request.number }} --comment "Finished
          applying Terraform changes. Closing the PR."
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

  get-kubeconfig:
    uses: opstella-playground/opstella-terraform-pipeline/.github/workflows/get-kubeconfig.yml@main
    needs: terraform-apply
    with:
      cluster_name: ${{ needs.terraform-apply.outputs.cluster_name }}
      resource_group: ${{ needs.terraform-apply.outputs.node_resource_group_name }}
      runner_label: ${{ inputs.runner_label }}
      azure_client_id: ${{ inputs.arm_client_id }}
      azure_tenant_id: ${{ inputs.arm_tenant_id }}
    secrets:
      AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
